### ISSUE TITLE
TypeError attempting to execute duckencoder.py

### ISSUE THREAD

**Issue by hazryder** [mame82/duckencoder.py#12]
I have my .duck script and duckencoder.py in the same directory.

When I run this command:

`python duckencoder.py -i rickroll.duck -o rickroll.bin`

I get the following TypeError:

```
E:\Data\Dev\RubberDucky\Scripts>python duckencoder.py -i rickroll.duck -o rickroll.bin
Traceback (most recent call last):
  File "duckencoder.py", line 571, in <module>
    main(sys.argv[1:])
  File "duckencoder.py", line 555, in main
    result = DuckEncoder.generatePayload(source, lang)
  File "duckencoder.py", line 380, in generatePayload
    payload = DuckEncoder.parseScript(source, keyboard, language)
  File "duckencoder.py", line 346, in parseScript
    l = l.strip().replace("\r\n", "").replace("\n", "")
TypeError: a bytes-like object is required, not 'str'
```

The contents of the .duck script are:

```
GUI r
STRING chrome.exe
ENTER
DELAY 2000
STRING youtube.com
ENTER
TAB
TAB
TAB
STRING never gonna give you up
ENTER
```

**Comment by thrust3d** [comment]
Did you solve it?

EDIT: use python 2
